-- Switch the heartbeat table from a single updated-in-place row to an
-- append-only log: each ping (see /api/heartbeat) inserts a new row. This
-- still keeps the Supabase free-tier project from auto-pausing due to
-- inactivity, and additionally leaves a history of pings. RLS stays enabled
-- with no policies, so only the service-role key (used server-side) can
-- read or write.

-- The old table used the Postgres "singleton table" pattern (boolean pk +
-- check constraint). There is no data worth preserving, so drop and recreate.
drop table if exists heartbeat;

create table heartbeat (
  id        bigint generated by default as identity primary key,
  pinged_at timestamptz not null default now()
);

alter table heartbeat enable row level security;
